multi-tenant:
  schedule:
    rate: PT1H           # Purge every 1 hour
  retry:
    max-attempts: 3            # Retry 3 times
    backoff: PT10S             # Retry every 10 seconds
    retryable-exceptions:
      - java.sql.SQLException
      - org.springframework.dao.DataAccessException
  deletion:
    interval: P1D              # Delete records older than 1 day


app:
  tenants:
    - tenantId: "1"
      tenantName: "INFOSYS"
      cron: "0 */2 * * * *"
      purge: true
    - tenantId: "2"
      tenantName: "TCS"
      cron: "0 */2 * * * *"
      purge: true

  tables:
    - tableName: "FleetData"
      retentionPeriod: "30d"
      clause: "status NOT IN ('In Progress', 'Approved')"
      group: 0
      subGroup: 0
    - tableName: "EmployeeRequests"
      retentionPeriod: "30d"
      clause: "status NOT IN ('In Progress', 'Approved')"
      group: 0
      subGroup: 0
