multi-tenant:
  schedule:
    rate: PT1H           # Purge every 1 hour
  retry:
    max-attempts: 3            # Retry 3 times
    backoff: PT10S             # Retry every 10 seconds
    retryable-exceptions:
      - java.sql.SQLException
      - org.springframework.dao.DataAccessException
  deletion:
    interval: P1D              # Delete records older than 1 day


app:
  tenants:
    - tenantId: "tenant1"
      tenantName: "Tenant One"
      cron: "0 0 * * *"
      purge: true
    - tenantId: "tenant2"
      tenantName: "Tenant Two"
      cron: "0 15 * * *"
      purge: false

  tables:
    - tableName: "table1"
      retentionPeriod: "30d"
      clause: "WHERE deleted = false"
      group: 0
      subGroup: 0
    - tableName: "table2"
      retentionPeriod: "90d"
      clause: "WHERE active = true"
      group: 0
      subGroup: 0
