app:
  tenants:
    - tenantId: "tenant1"
      tenantName: "Tenant One"
      cron: "0 0 * * *"
      purge: true
    - tenantId: "tenant2"
      tenantName: "Tenant Two"
      cron: "0 15 * * *"
      purge: false

  tables:
    - tableName: "table1"
      retentionPeriod: "30d"
      clause: "WHERE deleted = false"
      group: 1
      subGroup: 0
    - tableName: "table2"
      retentionPeriod: "90d"
      clause: "WHERE active = true"
      group: 2
      subGroup: 1
