global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  #  - job_name: 'prometheus'
  #    static_configs:
  #      - targets: [ 'localhost:9090' ]

  - job_name: 'test-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8180' ]

  - job_name: 'generate-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8182' ]

  - job_name: 'tokenize-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8184' ]

  # grpc applications, listen to separate management ports
  - job_name: 'evaluate-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8191' ]

  - job_name: 'calculator-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8193' ]
